[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
authors = ["Pashkov K.V. <pk69@kruger.su>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.28.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
